name: Go

on:
  push:
    tags: 
      - "v*"

jobs:

  build:
    name: Build Binary
    runs-on: macos-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19
      id: go

    - name: show Go verion
      run: go version

    # - name: Get dependencies
    #   run: |
    #     go get -v -t -d ./...
    #     if [ -f Gopkg.toml ]; then
    #         curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    #         dep ensure
    #     fi

    # - name: Show Environment Variables
    #   run: env

    - name: Build Binary
      run: make buildx
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          out/*
